alias: 'Garage lights on when overhead door is open'
trigger:
  - platform: state
    entity_id: sensor.garage_door_state
    to: 'open'
action:
  service: homeassistant.turn_on
  entity_id: script.timed_light
