alias: "Garage delay lights off after no movement and overhead door is closed"
trigger:
  - platform: state
    entity_id: binary_sensor.aeotec_zw074_multisensor_gen5_sensor_2_0
    to: 'off'
  - platform: state
    entity_id: sensor.garage_door_state
    to: 'closed'
action:
  service: homeassistant.turn_on
  entity_id: script.timer_off
